### PR TITLE
Bex north edge

### PR DESCRIPTION
**Pull request by BexDunn**
ok, I think we have the north edge test in here now? tests and linting passed.

### CODE REVIEW

**Comment by MatthewJA** [comment]
@BexDunn What changed in waterbodies_canberra.shp?

**Comment by BexDunn** [comment]
The original waterbodies_canberra.shp I think didn't contain the waterbodies that overlapped the tile boundaries, so I added one from the waterbodies shapefile. I was going to use a snippet of the waterbodies shapefile, but they were all much larger, and I think you said this way works better.

**Comment by BexDunn** [comment]
image

**Comment by BexDunn** [comment]
or, more usefully, uid r3cbj7d6s

**Pull request merged**
